plugins {
    id 'java'
}

group 'org.start2do'
version '2.0.9.2.10-SNAPSHOT'


dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    compileOnly("org.slf4j:slf4j-api:2.0.5")
    compileOnly group: 'io.ebean', name: 'ebean-annotation', version: '8.4'
    compileOnly 'jakarta.validation:jakarta.validation-api:2.0.2'
    testImplementation("org.mapstruct:mapstruct:$mapstructVersion")
    testImplementation("org.slf4j:slf4j-simple")
    testImplementation("org.slf4j:slf4j-api")
    compileOnly group: 'net.java.dev.jna', name: 'jna', version: '5.14.0'
    compileOnly("org.springframework:spring-web:5.3.19")
    compileOnly('javax.servlet:javax.servlet-api:4.0.1')
    compileOnly "com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion"
//
    compileOnly 'org.apache.commons:commons-compress:1.27.1'
//    compileOnly 'net.openhft:chronicle-map:3.22.9'
//    implementation 'net.openhft:chronicle-map:3.22.9'
//    testImplementation 'net.openhft:chronicle-map:3.22.9'
//    testImplementation 'org.apache.commons:commons-lang3:3.17.0'
//    compileOnly 'org.apache.commons:commons-lang3:3.17.0'


}

test {
    useJUnitPlatform()
}
