rootProject.name = 'start2do-util'
include 'bean-valiate'
include 'spring-util'
include 'pdf-util'
include 'ebean-common'
include 'spring-common'
include 'spring-security-api'
include 'common-util'
include 'spring-security-core'
include 'kaptcha'
include 'spring-business'
include 'code-gen'
include 'email'
include 'api'
include 'snmp-starter'
include 'snmp-util'
include 'clickhouse-dataSource'
include 'http-log-sdk'
include 'multiple-datasource-util'
include 'zl-media-kit-util'
include 'sso-login'
include 'sso-login-test'
include 'script-util'
include 'script-util:script-js-impl'
include 'updater'
include 'muilt-redis'
findProject(':script-util:script-js-impl')?.name = 'script-js-impl'
include 'common-redis'
include 'ops'

include 'script-util'
include ':script-util:script-common'
findProject(':script-util:script-common')?.name = 'script-common'
include ':script-util:script-js-impl'
findProject(':script-util:script-js-impl')?.name = 'script-js-impl'
include ':script-util:script-av-impl'
findProject(':script-util:script-av-impl')?.name = 'script-av-impl'
include ':script-util:script-js-nashorn-impl'
findProject(':script-util:script-js-nashorn-impl')?.name = 'script-js-nashorn-impl'
