plugins {
    id 'java'
    id 'java-library'
}

group = 'org.start2do'
version = '2.0.9.2.10-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    api("com.github.ben-manes.caffeine:caffeine:3.1.8")
    compileOnly("org.slf4j:slf4j-api:2.0.5")
    compileOnly(project(":common-util"))
    compileOnly 'com.googlecode.aviator:aviator:5.4.3'

    compileOnly group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: jacksonVersion
    compileOnly("com.zaxxer:HikariCP:6.2.1")
    compileOnly 'com.squareup.okhttp3:okhttp:4.12.0'
    compileOnly("com.squareup.okhttp3:logging-interceptor:4.12.0")


    testImplementation 'com.googlecode.aviator:aviator:5.4.3'
    testImplementation "com.fasterxml.jackson.core:jackson-annotations:$jacksonVersion"
    testImplementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: jacksonVersion
    testImplementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: jacksonVersion
    testImplementation("org.slf4j:slf4j-api")
    testImplementation("org.slf4j:slf4j-simple")
    testImplementation(project(":common-util"))

}

test {
    useJUnitPlatform()
}
