plugins {
    id 'java'
    id "org.springframework.boot" version "3.0.6"
}

group 'org.start2do'
version '3.0.6.1-SNAPSHOT'

dependencies {
    testImplementation 'org.testng:testng:7.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    implementation(project(":spring-common"))
    implementation(project(":bean-valiate"))
    implementation(project(":kaptcha"))
    api(project(":spring-security-api"))
    api(project(":common-util"))
    implementation(project(":spring-util"))
    compileOnly("org.springframework.boot:spring-boot:$springBootVersion")

    api 'io.jsonwebtoken:jjwt-api:0.11.5'
    api 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    compileOnly group: 'jakarta.servlet', name: 'jakarta.servlet-api', version: '6.0.0'
    compileOnly("org.springframework:spring-webmvc:$springVersion")
    api "org.springframework.boot:spring-boot-starter-security:$springBootVersion"
    compileOnly("org.springframework.boot:spring-boot-starter-data-redis:$springBootVersion")
    compileOnly("org.springframework.boot:spring-boot:$springBootVersion")
    compileOnly group: 'org.springframework', name: 'spring-jdbc', version: springVersion

}

test {
    useJUnitPlatform()
}
