plugins {
    id("java")
    id("java-library")
}

group = "org.start2do"
version = "3.0.5.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    compileOnly(project(":script-util:script-common"))
    compileOnly(project(":common-util"))
    compileOnly("org.slf4j:slf4j-api")
    compileOnly("com.github.ben-manes.caffeine:caffeine")
    compileOnly("org.openjdk.nashorn:nashorn-core:15.6")

}

tasks.test {
    useJUnitPlatform()
}
