spring:
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: 127.0.0.1
server:
  port: 9090
management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
