-- apply changes
create table sys_dept (
  id                            number(10) generated by default as identity (start with 10) not null,
  name                          varchar2(128),
  sort                          number(10),
  parent_id                     number(10),
  create_time                   timestamp not null,
  create_person                 varchar2(255) not null,
  update_time                   timestamp not null,
  update_person                 varchar2(255) not null,
  version                       number(19) not null,
  constraint uq_sys_dept_parent_id unique (parent_id),
  constraint pk_sys_dept primary key (id)
);

create table sys_menu (
  id                            number(10) generated by default as identity (start with 100) not null,
  name                          varchar2(128),
  path                          varchar2(255),
  permission                    varchar2(128),
  icon                          varchar2(255),
  sort                          varchar2(255),
  parent_id                     number(10),
  type                          varchar2(2),
  create_time                   timestamp not null,
  create_person                 varchar2(255) not null,
  update_time                   timestamp not null,
  update_person                 varchar2(255) not null,
  version                       number(19) not null,
  constraint ck_sys_menu_type check ( type in ('0','1','2')),
  constraint pk_sys_menu primary key (id)
);
comment on column sys_menu.type is '类型';

create table sys_role (
  id                            number(10) generated by default as identity (start with 100) not null,
  name                          varchar2(128),
  role_code                     varchar2(255),
  descs                         varchar2(255),
  create_time                   timestamp not null,
  create_person                 varchar2(255) not null,
  update_time                   timestamp not null,
  update_person                 varchar2(255) not null,
  version                       number(19) not null,
  constraint pk_sys_role primary key (id)
);

create table sys_role_menu (
  role_id                       number(10) not null,
  menu_id                       number(10) not null,
  constraint pk_sys_role_menu primary key (role_id,menu_id)
);

create table sys_setting (
  id                            number(19) generated by default as identity not null,
  enable                        varchar2(2),
  remark                        varchar2(512),
  type                          varchar2(128),
  kkey                          varchar2(128),
  vvalue                        varchar2(2048),
  sort                          number(10),
  create_time                   timestamp not null,
  create_person                 varchar2(255) not null,
  update_time                   timestamp not null,
  update_person                 varchar2(255) not null,
  version                       number(19) not null,
  constraint ck_sys_setting_enable check ( enable in ('1','0')),
  constraint IDX_ST_TYPE unique (type),
  constraint pk_sys_setting primary key (id)
);
comment on table sys_setting is '字典值表';

create table sys_user (
  id                            number(10) generated by default as identity (start with 100) not null,
  username                      varchar2(128),
  real_name                     varchar2(32),
  password                      varchar2(128),
  status                        varchar2(1) default '1',
  email                         varchar2(128),
  avatar                        varchar2(2048),
  phone                         varchar2(32),
  dept_id                       number(10),
  create_time                   timestamp not null,
  create_person                 varchar2(255) not null,
  update_time                   timestamp not null,
  update_person                 varchar2(255) not null,
  version                       number(19) not null,
  constraint ck_sys_user_status check ( status in ('1','0')),
  constraint pk_sys_user primary key (id)
);

create table sys_user_permission (
  menu_id                       number(10),
  user_id                       number(10) not null,
  menuId                        number(10) not null,
  constraint pk_sys_user_permission primary key (user_id,menuId)
);

create table sys_user_role (
  user_id                       number(10) not null,
  role_id                       number(10) not null,
  constraint pk_sys_user_role primary key (user_id,role_id)
);

-- foreign keys and indices
alter table sys_dept add constraint fk_sys_dept_parent_id foreign key (parent_id) references sys_dept (id);

create index ix_sys_menu_parent_id on sys_menu (parent_id);
alter table sys_menu add constraint fk_sys_menu_parent_id foreign key (parent_id) references sys_menu (id);

create index ix_sys_role_menu_role_id on sys_role_menu (role_id);
alter table sys_role_menu add constraint fk_sys_role_menu_role_id foreign key (role_id) references sys_role (id);

create index ix_sys_role_menu_menu_id on sys_role_menu (menu_id);
alter table sys_role_menu add constraint fk_sys_role_menu_menu_id foreign key (menu_id) references sys_menu (id);

create index ix_sys_user_dept_id on sys_user (dept_id);
alter table sys_user add constraint fk_sys_user_dept_id foreign key (dept_id) references sys_dept (id);

create index ix_sys_user_role_user_id on sys_user_role (user_id);
alter table sys_user_role add constraint fk_sys_user_role_user_id foreign key (user_id) references sys_user (id);

create index ix_sys_user_role_role_id on sys_user_role (role_id);
alter table sys_user_role add constraint fk_sys_user_role_role_id foreign key (role_id) references sys_role (id);

